### PR TITLE
Yardforce 500B

### PR DESCRIPTION
**Pull request by Janrupf**
## About

This is a work-in-progress attempt at supporting the Yardforce 500B variant. The biggest change seems to be that it is using a STM32F4, which in parts is different from the STM32F1 found in the original.

**The code in here has not been tested other than "it compiles", if you own a 500B feedback is welcome but flash at your own risk!**

I'm drafting this PR in order to track merge conflicts and coordinate integration.

The code in this PR is by no means my work alone and a lot of it has been sourced from the following repositories:
- https://github.com/slashphotos/Mowgli
- https://github.com/theely/B005CSerial

## Building

This PR retains support for both boards, the original variant is still the default target. Build a B variant firmware using `pio run -e Yardforce500B`

### CODE REVIEW

**Comment by cedbossneo** [comment]
Maybe we can refactor the actual code to support the two variants.

**Comment by Janrupf** [comment]
> Maybe we can refactor the actual code to support the two variants.

Thats essentially what this PR is doing - by selecting the appropriate board with PIO you can select for which mower you want to build.

**Comment by hpkevertje** [comment]
I've got Janruf's fork running on a 500B. Overall the mower is functioning, with some minor issues (I can't get the 'J18' debug to work, not all buttons on the pnnel work,...). Some of these might be because of me...
If you are still looking for feedback, I'm happy to provide it. I would need some guidance on what exactly to test and report.

**Comment by Janrupf** [comment]
Well, the general stance seems to be "it works" - as long as it doesn't blow up mainboards anymore (it shouldn't), the merge conflicts will need to be resolved and I think then it'd be ready to go.

Problem is, I don't have a 600B anymore. After my mainboard blew up, I swapped it for a 600 one

**Comment by danou07** [comment]
I have a 500B I installed the firmware from "Janrupf", in manual mode the robot works well, but in auto it goes in circles and stops.
I don't know what to do

**Comment by hpkevertje** [comment]
Hi @danou07 ,
what you describe doesn't sound like a firmware issue. If you can drive manually the firmware is installed and works fine.
The behavior you describe is possibly caused by an issue with the IMU (non-supported IMU, wrong wiring,...). Look in openmower-gui to see if you get readings and take it from there. Also make sure you have a supported IMU chip.
You're better off asking these kind of questions on Discord. You'll get the answers from the right people there and they are very helpfull.
Han

**Comment by cedbossneo** [comment]
This PR is still draft, do you think we can merge it ?

**Comment by Janrupf** [comment]
I _think_ so? The only real problem it ever had was blowing up the charging mosfet, but from what I've heard on the discord this issue has not been occurred ever again after the CPU clock fixes have been merged into this PR

**Comment by jeremysalwen** [comment]
There are still merge conflicts. I can resolve them and test on my 500B if you would like.

**Comment by Janrupf** [comment]
That would be awesome!

**Comment by cedbossneo** [comment]
I'm currently testing this PR on my classic but it doesn't work yet

**Comment by Janrupf** [comment]
Chances are something is broken for the non-B variant? I'm unsure and I can't really test anymore

**Comment by Alepat62** [comment]
I've been using Janrup's firmware for a couple of weeks now and it works well !
I only needed to add a delay at the IMU initialisation (I'm using a AltIMU-10 V5) otherwize I cannot see any values in the gui.

**Comment by jeremysalwen** [comment]
I have rebased the branch on the lastest master, and I reviewed the code since Janrupf's original commits to see if I could find the breaking change for 500 classic.

There were three spots that stood out to me: 

https://github.com/cedbossneo/Mowgli/pull/7/commits/dcbb41a98c82d16551bed3d440132e92039ff914#diff-2e268f72ab0f890272367bd327d3b2d8c602894458640ae128f581195b127fc4L103

removes __HAL_RCC_PWR_CLK_ENABLE() which is not removed in the main branch.

https://github.com/cedbossneo/Mowgli/pull/7/commits/13e0cf9558f9840bc5d79281563c7002c24debe2 and  https://github.com/cedbossneo/Mowgli/pull/7/commits/daa4e423fe651de156615e49469a49a95e91a009 both change how USART's are initialized in a way that the main branch hasn't.

I do not understand the code well enough to determine if these changes are good or bad, but if someone could look at them I suspect one of them is causing the issues with the 500 Classic.

**Comment by Janrupf** [comment]
https://github.com/cedbossneo/Mowgli/commit/dcbb41a98c82d16551bed3d440132e92039ff914#diff-2e268f72ab0f890272367bd327d3b2d8c602894458640ae128f581195b127fc4L103 - that may very well break it! I think the other 2 changes are fine (and should probably even be there for the non B variant?)

**Comment by jeremysalwen** [comment]
Thanks @Janrupf !  Here is the rebased branch with the tentative bugfix: https://github.com/jeremysalwen/Mowgli/tree/yardforce-500b .  I will try to test it on my 500b in a bit, but if someone could test it on their 500 classic that would be great!

**Comment by jeremysalwen** [comment]
I just tested it, working good on my 500B. The new pull request is here: https://github.com/cedbossneo/Mowgli/pull/12

**Comment by Alepat62** [comment]
> I just tested it, working good on my 500B. The new pull request is here: #12

Tested on mine, it works too !

**Comment by Janrupf** [comment]
Alright! Closing in favor of #12

**Pull request closed without merging**
